import { loadStyleRules } from './rules.js';
import { getPreset } from './presets.js';

// Comprehensive Unicode regex for Emojis and decorative symbols
const EMOJI_AND_SYMBOLS_REGEX = /(?:[\u{1F300}-\u{1FAFF}]|[\u{1F1E6}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{FE00}-\u{FE0F}]|[\u{1F900}-\u{1F9FF}]|[\u{1F600}-\u{1F64F}]|[\u{1F680}-\u{1F6FF}]|[\u{2300}-\u{23FF}]|[✅❌✔✖➤➔►✓✗ℹ️⚠️💡🔥✨🚀⭐🎉])/gu;

/**
 * Lints and optionally auto-fixes markdown content per PRD Section 7.
 *
 * @param {string} markdown
 * @param {object} options
 * @param {string} [options.style='plain']
 * @param {string} [options.lang='en']
 * @param {boolean} [options.fix=true]
 * @returns {{ output: string, score: number, violations: Array<{ rule: string, line: number, message: string }>, isClean: boolean }}
 */
export function lintMarkdown(markdown, options = {}) {
  const styleName = options.style || 'plain';
  const preset = getPreset(styleName);
  const lang = options.lang || 'en';
  const shouldFix = options.fix !== false;

  const rules = loadStyleRules();
  const violations = [];

  if (!markdown) {
    return { output: '', score: 100, violations: [], isClean: true };
  }

  const lines = markdown.split(/\r?\n/);
  let inCodeBlock = false;
  let codeBlockLang = '';

  const processedLines = [];
  let sectionCount = 0;

  // First pass: line-by-line checks
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];
    const lineNum = i + 1;

    // Check code blocks boundary
    if (line.trim().startsWith('```')) {
      if (!inCodeBlock) {
        inCodeBlock = true;
        codeBlockLang = line.trim().slice(3).trim();
      } else {
        inCodeBlock = false;
        codeBlockLang = '';
      }
      processedLines.push(line);
      continue;
    }

    if (inCodeBlock) {
      // Remove decorative comments generated by tools in code blocks if fix enabled
      if (shouldFix) {
        if (/^\s*(\/\/|#)\s*(Step \d+|Install dependencies|Run the app|Clone repo)/i.test(line)) {
          violations.push({
            rule: 'no-decorative-code-comment',
            line: lineNum,
            message: `Decorative comment in code block: "${line.trim()}"`,
          });
          continue; // omit the decorative comment
        }
      }
      processedLines.push(line);
      continue;
    }

    // 1. Emoji check
    if (!preset.allowEmojis) {
      if (EMOJI_AND_SYMBOLS_REGEX.test(line)) {
        violations.push({
          rule: 'no-emoji',
          line: lineNum,
          message: `Emoji or decorative symbol detected on line ${lineNum}`,
        });
        if (shouldFix) {
          line = line.replace(EMOJI_AND_SYMBOLS_REGEX, '').replace(/\s{2,}/g, ' ');
        }
      }
    }

    // 2. Headings deeper than ###
    const deepHeadingMatch = line.match(/^(#{4,})\s+(.*)$/);
    if (deepHeadingMatch) {
      violations.push({
        rule: 'heading-depth',
        line: lineNum,
        message: `Heading deeper than ### detected: "${line}"`,
      });
      if (shouldFix) {
        line = `### ${deepHeadingMatch[2]}`;
      }
    }

    if (/^##\s+/.test(line)) {
      sectionCount++;
    }

    // 3. Repeated bold list pattern: "- **Label**: text"
    const boldListMatch = line.match(/^(\s*[-*]\s*)\*\*([^*]+)\*\*:\s*(.*)$/);
    if (boldListMatch) {
      violations.push({
        rule: 'no-bold-list-labels',
        line: lineNum,
        message: `Repetitive bold list label detected: "- **${boldListMatch[2]}**:"`,
      });
      if (shouldFix) {
        line = `${boldListMatch[1]}${boldListMatch[2]}: ${boldListMatch[3]}`;
      }
    }

    // 4. Em-dash check
    if (preset.replaceEmDashes && (line.includes('—') || line.includes('&mdash;'))) {
      violations.push({
        rule: 'no-em-dash',
        line: lineNum,
        message: `Em-dash detected on line ${lineNum}`,
      });
      if (shouldFix) {
        line = line.replace(/—/g, ' - ').replace(/&mdash;/g, ' - ');
      }
    }

    // 5. Exclamation marks in prose (excluding markdown images, HTML comments, and inline code)
    if (preset.stripExclamations) {
      const images = [];
      const comments = [];
      const inlineCodes = [];

      let masked = line.replace(/`([^`]+)`/g, (match) => {
        inlineCodes.push(match);
        return `__CODE_${inlineCodes.length - 1}__`;
      });
      masked = masked.replace(/<!--[\s\S]*?-->/g, (match) => {
        comments.push(match);
        return `__COMMENT_${comments.length - 1}__`;
      });
      masked = masked.replace(/!\[([^\]]*)\]\(([^)]*)\)/g, (match) => {
        images.push(match);
        return `__IMG_${images.length - 1}__`;
      });

      if (masked.includes('!')) {
        violations.push({
          rule: 'no-exclamation',
          line: lineNum,
          message: `Exclamation mark detected on line ${lineNum}`,
        });
        if (shouldFix) {
          let stripped = masked.replace(/!+/g, '.').replace(/\.{2,}/g, '.');
          stripped = stripped.replace(/__IMG_(\d+)__/g, (_, idx) => images[Number(idx)]);
          stripped = stripped.replace(/__COMMENT_(\d+)__/g, (_, idx) => comments[Number(idx)]);
          line = stripped.replace(/__CODE_(\d+)__/g, (_, idx) => inlineCodes[Number(idx)]);
        }
      }
    }

    // 6. Forbidden words
    const wordsList = rules.forbiddenWords[lang] || rules.forbiddenWords.en || [];
    for (const forbidden of wordsList) {
      const wordRegex = new RegExp(`\\b${escapeRegExp(forbidden)}\\b`, 'gi');
      if (wordRegex.test(line)) {
        violations.push({
          rule: 'forbidden-word',
          line: lineNum,
          message: `Forbidden promotional/cliche word "${forbidden}" on line ${lineNum}`,
        });
        if (shouldFix) {
          line = line.replace(wordRegex, '');
          line = line.replace(/,\s*,+/g, ',').replace(/^\s*,\s*/, '').replace(/\s{2,}/g, ' ');
        }
      }
    }

    // 7. Forbidden structural patterns
    if (rules.forbiddenPatterns) {
      for (const pattern of rules.forbiddenPatterns) {
        const patRegex = new RegExp(pattern, 'i');
        if (patRegex.test(line)) {
          violations.push({
            rule: 'forbidden-pattern',
            line: lineNum,
            message: `Forbidden structural pattern matching "${pattern}" on line ${lineNum}`,
          });
          if (shouldFix) {
            line = line.replace(patRegex, '').trim();
          }
        }
      }
    }

    processedLines.push(line);
  }

  let finalMarkdown = processedLines.join('\n');

  // 8. Table of Contents threshold removal
  const totalLines = processedLines.filter((l) => l.trim().length > 0).length;
  const isShortDoc = totalLines < preset.tocThresholdLines && sectionCount <= preset.tocThresholdSections;

  if (isShortDoc && !preset.forceToc) {
    // Remove Table of Contents if present
    const tocRegex = /##\s+(?:Table of Contents|Daftar Isi)[\s\S]*?(?=\n##\s+|$)/i;
    if (tocRegex.test(finalMarkdown)) {
      violations.push({
        rule: 'unnecessary-toc',
        line: 1,
        message: `Table of Contents removed because document is concise (${totalLines} lines, ${sectionCount} sections).`,
      });
      if (shouldFix) {
        finalMarkdown = finalMarkdown.replace(tocRegex, '');
      }
    }
  }

  // Normalize excessive blank lines (more than 2 consecutive newlines)
  if (shouldFix) {
    finalMarkdown = finalMarkdown.replace(/\n{3,}/g, '\n\n').trim() + '\n';
  }

  // Calculate style score: 100 - (violations * 5), minimum 0
  const score = Math.max(0, 100 - violations.length * 5);
  const isClean = violations.length === 0;

  return {
    output: shouldFix ? finalMarkdown : markdown,
    score,
    violations,
    isClean,
  };
}

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
